spring:
  config:
    activate:
      on-profile: dev
  application:
    name: ${PRODUCT_SERVICE_NAME}
  datasource:
    username: ${USER_NAME}
    password: ${PASSWORD}
    url: ${PRODUCT_DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      port: ${REDIS_PORT}
      host: ${REDIS_HOST}

server:
  port: ${PRODUCT_SERVER_PORT}

eureka:
  client:
    service-url:
      defaultZone: ${DEFAULT_ZONE}

management:
  endpoints:
    web:
      exposure:
        include: refresh
