
spring:
  application:
    name: ${SERVER_NAME}
server:
  port: ${SERVER_PORT}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${SERVER_DEFAULT_ZONE}
  instance:
    hostname: ${HOST_NAME}
