spring:
  profiles:
    active: dev
  application:
    name: gateway-server

  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/order/**
        - id: product-service
          uri: http://localhost:19093
          predicates:
            - Path=/api/v1/products/**
        - id: auth-service
          uri: http://localhost:19095
          predicates:
            - Path=/api/v1/auth/**
      discovery:
        locator:
          enabled: true
