spring:
  config:
    activate:
      on-profile: dev

server:
  port: 19091

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
  instance:
    prefer-ip-address: true


service:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
