
spring:
  config:
    activate:
      on-profile: dev
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path= /api/v1/products/**

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path= /api/v1/auth/**
      discovery:
        locator:
          enabled: true

server:
  port: 19091

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/


service:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
